#----------------------
#     admin模块配置
#----------------------

#加载公共配置
spring:
  profiles:
    include: common

#服务器配置
server:
  port: 8080
  display-name: 理财后台管理系统

#日志路径（本地开发环境请自定义路径）
logging:
  path: /opt/logs/lc_admin
